TT2-1906: Updating to govuk-one-login/devplatform-upload-action version 3.8.1
govuk-one-login/txma-ticf-integration pull request #443
Opened 2024-07-10 13:52 UTC by richa-misra

- **Ticket Number**: #[TT2-1906](https://govukverify.atlassian.net/browse/TT2-1906) :ticket:

## :bulb: Description
Updating to govuk-one-login/devplatform-upload-action version 3.8.1

2024-07-10 14:06 UTC, nacnudus approved these changes

2024-07-11 10:14 UTC, zaydgds requested changes
I'd avoid upgrading this till we update the mock integration server which you closed https://github.com/govuk-one-login/txma-ticf-integration-mock-server/pull/121

2024-07-11 11:32 UTC, eearcher-gds submitted a review, later dismissed

2024-07-11 12:26 UTC, richa-misra commented
> I'd avoid upgrading this till we update the mock integration server which you closed [govuk-one-login/txma-ticf-integration-mock-server#121](https://github.com/govuk-one-login/txma-ticf-integration-mock-server/pull/121)

thats not the right mock-server PR, its https://github.com/govuk-one-login/txma-ticf-integration-mock-server/pull/122

2024-07-11 12:58 UTC, zaydgds approved these changes

2024-07-11 14:49 UTC, eearcher-gds approved these changes

2024-07-15 09:15 UTC, merged